### ISSUE TITLE
Weather wrong, though location is correct....

### ISSUE THREAD

**Issue by frohro** [pedronveloso/android-digital-frame#3]
This morning the weather said it was snowing, but it isn't!  I went and checked the latitude and longitude.  See the photos.
![PXL_20240328_141438960](https://github.com/pedronveloso/android-digital-frame/assets/994565/4a5b77d9-8c87-44eb-9775-6b078db67b54)
![PXL_20240328_140411856 MP](https://github.com/pedronveloso/android-digital-frame/assets/994565/a9ca1572-839a-487b-b833-ed133a0e4e36)

**Comment by pedronveloso** [comment]
Interesting. I don't think the coordinates would change on their own, I will look at the code to see if there's a mismatch between the icon and the weather code.

I'm thinking a feature that would come in handy is to collect logs locally and allow them to be sent over by as an attachment by email or other routes. I'll build that into the next version, with logs it would be easier to tell how that happened.

**Comment by pedronveloso** [comment]
While I have no good way of knowing what caused the issue that time, I've added logs into the app for an easier way to tell next time something like that happens. You can inspect and send them next time around by going into Settings > General > App Logs.
The code on this page determine what ends up being displayed as Snow on the app: https://openweathermap.org/weather-conditions
In the instance of the app that you had, anything between `600` and `622` would present as snow. So its possible that the weather reported for your area could have mapped to a value there, which shouldn't be interpreted as "snowing". My gut is telling me this is the most likely cause. The weather code being fetched will be logged, and it should be easier to determine which of those values should be interpreted as something else next time.
I'm closing this issue for now, but feel free to reopen or open a new one if/when you have more info.



New release and notes here: https://github.com/pedronveloso/android-digital-frame/releases/tag/0.0.8

**Comment by frohro** [comment]
Cool!  When I get home, I'll update my phones.

**Comment by frohro** [comment]
Sounds great to me Pedro.  I'm really enjoying the photos and actually using the weather too.
Thanks!
Rob

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
